export const UI_TEXT = {
  gameTitle: 'IDLE CLICKER',
  tapButton: 'TAP',
  storeTitle: 'STORE',
  metaUpgradesTitle: 'UPGRADES',
  statusTitle: 'STATUS',
  prestigeTitle: 'PRESTIGE',
  prestigeAction: 'PRESTIGE',
  prestigeConfirmTitle: 'CONFIRM PRESTIGE',
  prestigeConfirmBody:
    'Soft reset this run? You keep Ascension Tokens, achievements and all-time stats. Coins, store levels and upgrades reset.',
  prestigeConfirmYes: 'PRESTIGE',
  prestigeConfirmNo: 'CANCEL',
  prestigeHint:
    'Soft reset: clears coins, store levels and upgrades. Keeps Ascension Tokens, achievements and all-time stats. Each token gives +1% idle.',
  prestigeEarnMore: 'Earn more coins this run to prestige',
  prestigeNowFor: 'Prestige now for +{count} Ascension Tokens',
  prestigeIdleBonus: 'Idle bonus from tokens: +{pct}%',
  prestigeCountLabel: 'Prestiges: {count}',
  prestigeCoinsThisRun: 'Coins this run: {coins}',
  ascensionTokens: 'Ascension Tokens',
  settingsTitle: 'SETTINGS',
  tabs: ['UPGRADES', 'STORE', 'TAP', 'STATUS', 'PRESTIGE'],
  tabsOverflow: '…',
  hudCoins: '{coins} coins',
  hudStats: 'per tap: {perTap} | coins / sec: {perSecond}',
  offlineAwayFor: 'Away for {duration}',
  offlineGain: '+{coins} coins',
  sound: 'SOUND',
  soundDescription: 'Sound effects for purchases',
  exportSave: 'EXPORT SAVE',
  exportSaveDescription: 'Copy a backup code to the clipboard',
  exportSavePrompt: 'Copy this save code:',
  importSave: 'IMPORT SAVE',
  importSaveDescription: 'Paste a backup code to restore',
  importSavePrompt: 'Paste your save code:',
  importSaveConfirmTitle: 'IMPORT SAVE?',
  importSaveConfirmBody: 'This replaces your current save. Continue?',
  importSaveConfirmYes: 'IMPORT',
  importSaveConfirmNo: 'CANCEL',
  toastSaved: 'Game saved',
  toastSaveFailed: 'Save failed',
  toastExported: 'Save copied to clipboard',
  toastExportFailed: 'Could not copy save',
  toastImported: 'Save imported',
  toastImportFailed: 'Invalid save code',
  toastImportEmpty: 'No save code pasted',
  toastAchievement: 'Achievement: {name}',
  tooltipAffordableNow: 'Affordable now',
  tooltipAffordableIn: 'Affordable in ',
  tooltipAffordableNever: 'Need idle income to afford',
  tooltipPayback: 'Payback ',
  on: 'ON',
  off: 'OFF',
  welcomeBack: 'WELCOME BACK',
  offlineEarnings: 'OFFLINE EARNINGS',
  continue: 'CONTINUE',
  start: 'Click to start',
  unlockHint: 'Keep progressing to unlock',
  statusGeneral: 'GENERAL',
  statusMultipliers: 'MULTIPLIERS',
  statusAchievements: 'ACHIEVEMENTS',
  statusCoinsBank: 'Coins in bank: {coins}',
  statusCoinsPrestige: 'Coins this prestige: {coins}',
  statusCoinsAllTime: 'Coins all time: {coins}',
  statusGeneratorsOwned: 'Generators owned: {count}',
  statusIdleRate: 'Idle (coins / sec): {rate}',
  statusPerTap: 'Per tap: {rate}',
  statusTotalTaps: 'Total taps: {count}',
  statusMetaMult: 'Meta upgrades: x{mult}',
  statusAchievementMult: 'Achievements: x{mult}',
  statusTokenMult: 'Ascension Tokens: x{mult} ({count})',
  statusCombinedMult: 'Combined idle: x{mult}',
  metaFallbackUpgrade: 'Upgrade',
  metaOwnGenerator: 'Own {count} of {label}',
  metaOwnTotal: 'Own {count} generators total',
  metaReachTaps: 'Reach {count} taps',
  metaEffectGenerator: '{label} x{mult}',
  metaEffectGlobal: 'All production x{mult}',
  metaEffectClickPerSecond: 'Tap +{pct}% of idle production',
  metaReachCoins: 'Earn {count} coins lifetime',
  tapPowerEffect: '+{value} tap power',
  autoTapEffect: '+{value} click / {seconds}s',
  generatorEffect: '+{value} coins / sec',
  generatorIdleShare: ' ({pct})',
  tooltipOwnedLabel: 'owned: ',
  tooltipCostLabel: 'cost ',
  tooltipProducesPrefix: 'Produces ',
  tooltipProducesSuffix: ' coins every second.',
  tooltipEachPrefix: 'each produces ',
  tooltipEachSuffix: ' coins / sec',
  tooltipTotalMid: ' producing ',
  tooltipTotalSuffix: ' coins / sec',
  tooltipTapPrefix: 'Adds +',
  tooltipTapSuffix: ' coins per tap.',
  tooltipAutoTapBefore: 'Clicks once every ',
  tooltipAutoTapMid: 's automatically (+',
  tooltipAutoTapAfter: ' cursor).',
};
